<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_kioskName</name>
   <tag></tag>
   <elementGuidId>a6d0c0f4-07d7-4aa0-807b-ab92ad7f89a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kioskName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kioskName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>152962be-156d-463b-810f-162b8919007e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec1e647b-6fdd-4b98-be38-b54fe608efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kioskName</value>
      <webElementGuid>874cd8e7-7d97-4e82-b15e-7e87d6933c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-auth required lettersonly input-kiosk input-capital error</value>
      <webElementGuid>d34c86af-c57f-48e4-bbaf-b429acc8cfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c5c842b0-dedb-4cac-b426-4bedfee1a8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>12d0d79a-9d27-4200-a26e-52c92c83aaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authForm&quot;)/div[@class=&quot;step-npwp-success&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/input[@class=&quot;input-auth required lettersonly input-kiosk input-capital error&quot;]</value>
      <webElementGuid>0cc81d2b-66f4-4f55-a943-60c01d73832f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kioskName']</value>
      <webElementGuid>d46e3f6e-f719-4fd2-a8b6-480aa028af30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authForm']/div/div/div/input</value>
      <webElementGuid>21c1f22b-c0fb-4ca3-8054-04492462ee92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b9e4e552-c996-40d2-ab51-9a2a4d292890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kioskName']</value>
      <webElementGuid>30adccb7-2fd6-47af-a934-dd010fc15e37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
