<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Silakan tunggu sebentar, sedang menghubungkan dengan server_videoParent</name>
   <tag></tag>
   <elementGuidId>c9c335fc-ca0d-426a-b790-0be7deb6f3ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#videoParent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='videoParent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>fb7bebf1-8439-47ef-9392-3c193000cd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>videoParent</value>
      <webElementGuid>94aeb27a-b783-4138-92cb-4c056aa367a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;videoParent&quot;)</value>
      <webElementGuid>b6508026-2009-4009-ab87-57fcf4142ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='videoParent']</value>
      <webElementGuid>121d5fc4-0a00-450f-ab0c-ce65c9ea8c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='HOME']/section/a/div/video</value>
      <webElementGuid>f6b94db8-edad-4c19-b2ec-8257f0c2fe22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan tunggu sebentar, sedang menghubungkan dengan server'])[1]/following::video[1]</value>
      <webElementGuid>3d09fd9c-1a0b-4049-98c4-2c6784f454e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang di CIMB Niaga Digital Lounge'])[1]/preceding::video[1]</value>
      <webElementGuid>44e64cc5-f112-49bd-bc94-9abed6b4ea2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik di manapun untuk memulai'])[1]/preceding::video[1]</value>
      <webElementGuid>e680a8a6-f364-4549-884e-494e87b9f382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>31004344-8a62-4d62-9d4a-5b96e15e9c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'videoParent']</value>
      <webElementGuid>c35e7557-7466-468c-bebc-141ec5b0a916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
