<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut Informasi Rekening</name>
   <tag></tag>
   <elementGuidId>c8813d3e-159e-407c-b501-cfeb7b263be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-red.btn-light-red.button--round-l.btn-data-next.no-margin.next-form.btn-show.on-form.progress-form.check-facta.progress-form.check-om-oc-registration.check-card-linkage.btn-to-linkage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffad7b06-2882-49db-aafd-2c79567e1cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0cbdc81b-b6c9-44a8-820f-23a3589cdd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-red btn-light-red button--round-l btn-data-next no-margin next-form btn-show on-form progress-form check-facta progress-form check-om-oc-registration check-card-linkage btn-to-linkage</value>
      <webElementGuid>56b1f80e-c7e9-477a-840b-6aee6ebe1d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-progress-form</name>
      <type>Main</type>
      <value>65%</value>
      <webElementGuid>2accba11-c36c-4f7d-89dc-b7f7b4acc8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-next</name>
      <type>Main</type>
      <value>SAXTRA-EXISTING-NO-BO-4</value>
      <webElementGuid>cdb1ea18-eb71-4ee5-8326-fec829c20ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canvas</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da59812a-98c3-4d83-99e8-4908692a21d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Lanjut
                                                            
                                                        </value>
      <webElementGuid>f4057927-1014-42fb-91b0-beab64fb39d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/section[@class=&quot;SAXTRA-EXISTING-NO-BO-3 remove-hide show&quot;]/div[@class=&quot;container-fluid add-blur&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;wrap-right&quot;]/div[@class=&quot;in-form&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/form[1]/div[@class=&quot;wrap-button&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;text-right&quot;]/button[@class=&quot;button btn-red btn-light-red button--round-l btn-data-next no-margin next-form btn-show on-form progress-form check-facta progress-form check-om-oc-registration check-card-linkage btn-to-linkage&quot;]</value>
      <webElementGuid>f9339d12-8c9b-4d32-adc7-821805e2095e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[5]</value>
      <webElementGuid>589a4648-ab19-44e1-ad3f-abf6fc60a79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FORM']/section[5]/div/div/div[2]/div/div[2]/div/div/form/div[2]/div/div[2]/div/button</value>
      <webElementGuid>9c91c173-32e1-4c83-8761-33f79941db3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[5]/following::button[1]</value>
      <webElementGuid>a95436a5-c563-4368-a797-47d1bebd8bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu akan dikenakan biaya Rp 2.000 / bulan.'])[1]/following::button[2]</value>
      <webElementGuid>346151bd-377b-49f0-afe3-196ec79ffc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda tangan pada kotak di bawah ini'])[1]/preceding::button[1]</value>
      <webElementGuid>11941d60-617f-437b-8e48-4dfce0674344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div[2]/div/div[2]/div/div/form/div[2]/div/div[2]/div/button</value>
      <webElementGuid>ffe5153b-b868-4357-9491-ae08703de697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                                            Lanjut
                                                            
                                                        ' or . = '
                                                            Lanjut
                                                            
                                                        ')]</value>
      <webElementGuid>b55bfb5e-8194-40ee-ae59-88ffd6dea3ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
