<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YA</name>
   <tag></tag>
   <elementGuidId>c105c1d2-dcf9-4d76-88ee-648c2b0e86b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-red.btn-light-red.uppercase.button--round-l.btn-data-next.no-margin.next-form.btn-show.on-form.progress-form.btn-yes-linkage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d8915a1-8684-44ae-a299-871cda9b4984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>122c1c39-cb34-4ff8-9dc8-2721975de39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-red btn-light-red uppercase button--round-l btn-data-next no-margin next-form btn-show on-form progress-form btn-yes-linkage</value>
      <webElementGuid>024992b7-93ec-46ab-bbfd-99f0b2f026e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-canvas</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4715f87-11ef-4850-ae3f-d93e1d0058d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-progress-form</name>
      <type>Main</type>
      <value>65%</value>
      <webElementGuid>512cc7b4-a085-4009-972b-23526b3d0b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            YA
                                        </value>
      <webElementGuid>f35bf81f-02a3-4b3d-96ed-8e115991c79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-linkage-pop&quot;)/div[@class=&quot;overlay&quot;]/div[@class=&quot;popup-content&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/form[1]/ul[@class=&quot;l-pop&quot;]/li[2]/div[@class=&quot;text-left&quot;]/button[@class=&quot;button btn-red btn-light-red uppercase button--round-l btn-data-next no-margin next-form btn-show on-form progress-form btn-yes-linkage&quot;]</value>
      <webElementGuid>1fc5c2d1-12ec-4147-bbca-88352ed588ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[21]</value>
      <webElementGuid>550b0441-e587-4fe7-8e75-db88ee7bfe7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-linkage-pop']/div/div/div/div/form/ul/li[2]/div/button</value>
      <webElementGuid>7436c83d-6642-45cd-a584-3e4a0a4c8881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIDAK'])[8]/following::button[1]</value>
      <webElementGuid>4b41a5db-3fd3-4c84-b12b-53b72d9d3d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya telah menerima Kartu ATM CIMBNiaga dengan nomor berikut :'])[1]/following::button[2]</value>
      <webElementGuid>ae31c3a5-903d-4469-b045-e2358191a0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor kartu ATM yang Anda masukkan tidak sesuai, mohon untuk dapat diulangi kembali.'])[1]/preceding::button[1]</value>
      <webElementGuid>b528a346-eeac-40f2-843d-0fc411cd8381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[2]/div/button</value>
      <webElementGuid>d7b2881b-e0c0-4347-abcc-b4fad6cc9f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                            YA
                                        ' or . = '
                                            YA
                                        ')]</value>
      <webElementGuid>9fd96695-081d-43e0-bd52-bde1e2fcbaec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
