<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lanjut_nomor_debit</name>
   <tag></tag>
   <elementGuidId>097e090c-2c94-4da8-b183-2c8906730223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nomor_debit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nomor_debit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>323664c8-d942-4ce8-b87c-3bc8ee7d0e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71f1d864-5bb2-4d68-ac77-54fdf305d57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b656c16c-5a7e-42ec-b253-97e637e6905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_debit</value>
      <webElementGuid>39440c4b-74ab-4e60-8f40-7b5aaf4ee9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required input-filled input-number only-number no-special input-debit input-capital</value>
      <webElementGuid>11eff5da-2ebd-4488-8939-d6c66d168aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>190ff4a5-8781-4b87-ba79-afb52b411e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>9cb055e5-dc54-433e-a482-fdf5ab5fbc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/section[@class=&quot;NEW-CARD-LINKAGE remove-hide show&quot;]/div[@class=&quot;bg-informasi add-blur&quot;]/div[@class=&quot;pad-info&quot;]/div[@class=&quot;box-info add-blur&quot;]/form[1]/div[@class=&quot;card-linkage&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;bdy-info&quot;]/div[@class=&quot;pos-rel&quot;]/input[@class=&quot;form-control required input-filled input-number only-number no-special input-debit input-capital&quot;]</value>
      <webElementGuid>92bc0dd4-00c6-47fb-838e-218809cf212a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nomor_debit']</value>
      <webElementGuid>e4f86048-37a5-4461-9fca-7c9c04aa29b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FORM']/section[15]/div/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>0e0bd974-87c9-4a48-8f21-0c49ceef0340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[15]/div/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>9e6ae310-79ec-4af0-b0a8-9be6d13eff74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nomor_debit']</value>
      <webElementGuid>643efa7e-1b68-4929-b5c0-ba6493b60bbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
