<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_informasi_existing_no_bo_novalas_setoran_awal</name>
   <tag></tag>
   <elementGuidId>6ad304ee-3b0b-4d77-827a-4ec2a26df124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='informasi_existing_no_bo_novalas_setoran_awal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;informasi_existing_no_bo_novalas_setoran_awal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbf01dda-aaf4-4c31-8df2-d5bc8675a81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a72df7e9-3777-428d-8ddb-a1acfa8045c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>265bc04f-0763-4c00-8429-e30980615fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>informasi_existing_no_bo_novalas_setoran_awal</value>
      <webElementGuid>d4626fb6-9799-48fe-8dfb-9537fc6387dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-filled pad-rp only-number input-capital required</value>
      <webElementGuid>8b8d2d81-38dd-4f1b-8d74-eb9183a6da8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-val</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a560ea99-bb6d-44fc-8eb2-68bf623d3f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-val</name>
      <type>Main</type>
      <value>9.999.999.999</value>
      <webElementGuid>7f22a662-cf38-465d-9ad9-8c83f365f14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/section[@class=&quot;SAXTRA-EXISTING-NO-BO-3 remove-hide show&quot;]/div[@class=&quot;container-fluid add-blur&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;wrap-right&quot;]/div[@class=&quot;in-form&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 sumber_dana&quot;]/div[2]/div[@class=&quot;form-group&quot;]/div[@class=&quot;pos-rel&quot;]/input[@class=&quot;form-control input-filled pad-rp only-number input-capital required&quot;]</value>
      <webElementGuid>2032cc03-bd83-4e38-b545-5ed0503bc7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='informasi_existing_no_bo_novalas_setoran_awal']</value>
      <webElementGuid>fa6ef86b-49db-4823-b47b-10e3995e14b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FORM']/section[5]/div/div/div[2]/div/div[2]/div/div/form/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>234026f0-2ca3-4c41-aca0-b4077dd65bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/input</value>
      <webElementGuid>2fb87fb3-4843-464d-8602-c96b04632a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'informasi_existing_no_bo_novalas_setoran_awal']</value>
      <webElementGuid>ae03f707-83aa-44b6-971a-f09f05514435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
