<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_YA</name>
   <tag></tag>
   <elementGuidId>a5da3a91-7af6-437a-a76b-661c8ccccb8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='card-linkage-pop']/div/div/div/div/form/ul/li[2]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-red.btn-light-red.uppercase.button--round-l.btn-data-next.no-margin.next-form.btn-show.on-form.progress-form.btn-yes-linkage > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d67af8bb-ac64-4fef-8954-da117b8884c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>button_ya</value>
      <webElementGuid>ec11bcda-1e4f-4d26-9c02-a393827f8707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YA</value>
      <webElementGuid>2aaf5ad1-5a71-4eff-88fb-79185cb8ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-linkage-pop&quot;)/div[@class=&quot;overlay&quot;]/div[@class=&quot;popup-content&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/form[1]/ul[@class=&quot;l-pop&quot;]/li[2]/div[@class=&quot;text-left&quot;]/button[@class=&quot;button btn-red btn-light-red uppercase button--round-l btn-data-next no-margin next-form btn-show on-form progress-form btn-yes-linkage&quot;]/span[1]</value>
      <webElementGuid>255bab95-97b4-4a27-b8d9-68888e0f63d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-linkage-pop']/div/div/div/div/form/ul/li[2]/div/button/span</value>
      <webElementGuid>dc8a0588-7fad-4fab-8e20-fb3ed116db21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIDAK'])[8]/following::span[1]</value>
      <webElementGuid>4962c27f-6a34-465e-9367-c757bacfb9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya telah menerima Kartu ATM CIMBNiaga dengan nomor berikut :'])[1]/following::span[2]</value>
      <webElementGuid>c1a27eec-2c15-449a-9c46-b229e36a359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor kartu ATM yang Anda masukkan tidak sesuai, mohon untuk dapat diulangi kembali.'])[1]/preceding::span[1]</value>
      <webElementGuid>c16dc942-0acb-4798-b885-53d48da2706c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut'])[21]/preceding::span[1]</value>
      <webElementGuid>df573c84-d5b0-471a-89d5-b707ef831370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[2]/div/button/span</value>
      <webElementGuid>c18295bb-fa23-44cd-a367-a73d3fd6d6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'YA' or . = 'YA')]</value>
      <webElementGuid>19f37a6d-e949-4e75-8a67-79dceb8ae594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
