<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TIDAK</name>
   <tag></tag>
   <elementGuidId>df03cc7d-a1b2-48bb-a3ac-03406465e799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='FORM']/section[5]/div/div/div[2]/div/div[2]/div/div/form/div/div[2]/div[2]/ul/li/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.option-card.nodis > ul.l-form > li > button.button.btn-red.btn-light-red.button--round-l.btn-show-debit-yes > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc88dbb9-2555-4a8e-9163-ec3e1ea76177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>button_tidak</value>
      <webElementGuid>f42fa870-5800-4ffa-b19c-74dedc7ac313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIDAK</value>
      <webElementGuid>46c9320a-b6d6-4f22-91a4-4d5872f014a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/section[@class=&quot;SAXTRA-EXISTING-NO-BO-3 remove-hide show&quot;]/div[@class=&quot;container-fluid add-blur&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;wrap-right&quot;]/div[@class=&quot;in-form&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 row-debit-card&quot;]/div[@class=&quot;form-group option-card nodis&quot;]/ul[@class=&quot;l-form&quot;]/li[1]/button[@class=&quot;button btn-red btn-light-red button--round-l btn-show-debit-yes&quot;]/span[1]</value>
      <webElementGuid>e6fe016f-6f45-4d25-9543-b5c3436ef8f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FORM']/section[5]/div/div/div[2]/div/div[2]/div/div/form/div/div[2]/div[2]/ul/li/button/span</value>
      <webElementGuid>781c0cf4-e89a-4bc1-8077-0d742dcb6abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda ingin menghubungkan rekening dengan kartu yang telah dimiliki?'])[1]/following::span[1]</value>
      <webElementGuid>97dc2add-5561-42f4-91dc-7fa4e90abd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YA'])[1]/following::span[1]</value>
      <webElementGuid>a5b2efd7-0438-4b5b-a845-c26d20bd5bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YA'])[2]/preceding::span[1]</value>
      <webElementGuid>8fd40b06-2a9d-4ffa-927b-3a904201ffff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Kartu Debit'])[1]/preceding::span[2]</value>
      <webElementGuid>47e17924-b3f7-4c1a-8293-de6aeca37889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/button/span</value>
      <webElementGuid>6aaadfe9-cc17-43d8-9cf5-173b56b37a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TIDAK' or . = 'TIDAK')]</value>
      <webElementGuid>6684a3ea-e069-4d06-8776-b9673e167304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
