<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit</name>
   <tag></tag>
   <elementGuidId>c05aa3f3-c352-45bc-8aac-ee4f1c04ca8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='FORM']/section[15]/div/div/div/form/div/div/div/div/div[3]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-red.btn-light-red.uppercase.button--round-l.submit-card-linkage > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ecc442a-196e-46ca-8a10-1becfbe390cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>button_submit</value>
      <webElementGuid>510513bb-1ee4-4f1b-a704-d876b79df09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>3d2ddf70-6a13-4e64-9adb-46543df52501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/section[@class=&quot;NEW-CARD-LINKAGE remove-hide show&quot;]/div[@class=&quot;bg-informasi add-blur&quot;]/div[@class=&quot;pad-info&quot;]/div[@class=&quot;box-info add-blur&quot;]/form[1]/div[@class=&quot;card-linkage&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;bdy-info&quot;]/div[@class=&quot;btn-submit&quot;]/button[@class=&quot;button btn-red btn-light-red uppercase button--round-l submit-card-linkage&quot;]/span[1]</value>
      <webElementGuid>5135d688-3c56-4c71-a36b-8facec5be254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='FORM']/section[15]/div/div/div/form/div/div/div/div/div[3]/button/span</value>
      <webElementGuid>5f7f5a4e-8d99-45dc-b348-1f5616077cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut'])[14]/following::span[1]</value>
      <webElementGuid>4e7fdd8f-15cf-49c7-9f85-9cfec38f5898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[14]/following::span[2]</value>
      <webElementGuid>14a73608-610b-4241-a9bc-aacf7919d8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[15]/preceding::span[1]</value>
      <webElementGuid>a6bf1fc5-adeb-4a96-8450-e3d72c9e1a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut'])[15]/preceding::span[2]</value>
      <webElementGuid>7322ddc4-21fa-4080-85e1-9ba4c0d23ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>0c806058-82b1-4b3b-a392-452422a06521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>2d8be0cf-bd64-4262-bb0c-6a5a3b928e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>78d0c9a4-8f09-42df-9d2f-8f0faf4540c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
