<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_keyboard</name>
   <tag></tag>
   <elementGuidId>a1f80e69-d99c-4252-beca-9eefeebe3a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBackdrop-root.jss490 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6eeb0699-7490-4c66-853d-5943f2db985d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cimb_tablet/assets/images/keyboard.png</value>
      <webElementGuid>c192d021-b346-4568-9758-c4c684f136a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss380&quot;]/div[@class=&quot;MuiBackdrop-root jss490&quot;]/img[1]</value>
      <webElementGuid>7fc808f1-9e1c-44e1-af35-bff2a0be7143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/img</value>
      <webElementGuid>d0347f69-362e-4d35-a428-04ddc90056a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>81e10c63-c4ed-4c6f-8a9d-770e2070eab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/cimb_tablet/assets/images/keyboard.png']</value>
      <webElementGuid>ce70d35d-64dd-40be-a37a-c8b168c59958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
