<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kartu debit Anda telah selesai dicetak</name>
   <tag></tag>
   <elementGuidId>371423f3-d2d4-4f9e-89f0-814a57ace949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.jss662.MuiTypography-body1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>10d13d3c-c06f-40d2-b925-386d17229e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root jss662 MuiTypography-body1</value>
      <webElementGuid>c841560d-7b2e-4fa8-8be9-e8145d989f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kartu debit Anda telah selesai dicetak.</value>
      <webElementGuid>63e1fb13-1f10-45b1-962f-99ee90d709d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;MuiContainer-root jss658 MuiContainer-maxWidthLg&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;MuiGrid-root jss660 MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;react-reveal&quot;]/p[@class=&quot;MuiTypography-root jss662 MuiTypography-body1&quot;]</value>
      <webElementGuid>b6489d5a-f6a2-4456-bae2-d4209ed67366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/p</value>
      <webElementGuid>fc956d60-34fe-4bd9-8c35-8990c8778ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::p[5]</value>
      <webElementGuid>e47eda5f-7ef5-4dff-8353-72d9236132ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/preceding::p[5]</value>
      <webElementGuid>41ce268f-533f-4cf7-8eec-0b1e3381e29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kartu debit Anda telah selesai dicetak.']/parent::*</value>
      <webElementGuid>f9b1458f-9978-42d1-913d-08d450f9dcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/p</value>
      <webElementGuid>967abd0e-718f-4f3b-9296-52c0a38777c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kartu debit Anda telah selesai dicetak.' or . = 'Kartu debit Anda telah selesai dicetak.')]</value>
      <webElementGuid>f0f993a6-fc5c-43fd-afe5-eb80389e0296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
