<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Loading_button btn-grey btn-red btn-_5d1c8f</name>
   <tag></tag>
   <elementGuidId>e3316e7f-44c8-41fe-946e-faf00465c083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-grey.btn-red.btn-light-red.button--round-l.no-margin.button-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d856aa0-3c7c-4b17-a908-372d23fce476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0ed30251-736f-4ba5-832b-5199bc569f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-grey btn-red btn-light-red button--round-l no-margin button-login</value>
      <webElementGuid>29a1f8ad-fa5e-44bf-9ce8-6fd21d3a6c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>ba1ce626-1962-4092-a132-42ea08647265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authForm&quot;)/div[@class=&quot;clearfix btn-fixed b20 next-block&quot;]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;button btn-grey btn-red btn-light-red button--round-l no-margin button-login&quot;]</value>
      <webElementGuid>48535cc1-a338-4d05-9d05-19e8fa8256a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='login']</value>
      <webElementGuid>da1faff9-182f-43e3-9442-8e8983290b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authForm']/div[2]/div/button</value>
      <webElementGuid>4b6d626d-6598-4eb9-a0a6-7df5780540f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading ...'])[1]/preceding::button[2]</value>
      <webElementGuid>e576f19e-2434-4a13-b7da-cd3c049a62f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a1d17207-857f-48ea-ab38-919f2a73a71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>fedabe5b-3a64-43b9-ac41-83256172f76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
