<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_kioskName</name>
   <tag></tag>
   <elementGuidId>baf4b592-fb9f-4f3a-9dda-905c23d8c6bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kioskName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kioskName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ef0675a-1fd0-4ae4-bd92-c51305cd3b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bba0ac6-f620-4fa6-a264-e907112eb308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kioskName</value>
      <webElementGuid>97e63e09-1c1e-4638-b5d1-067ead6bcb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-auth required lettersonly input-kiosk input-capital error</value>
      <webElementGuid>0e211d3e-dd92-49bb-b6e7-6cb69a1cf38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>73b6fa43-0219-4c4f-976f-69622ae02da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>97d16f1d-4e7e-4e78-b9a3-84d9614de828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authForm&quot;)/div[@class=&quot;step-npwp-success&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/input[@class=&quot;input-auth required lettersonly input-kiosk input-capital error&quot;]</value>
      <webElementGuid>1dd4f9d0-a0f2-48e3-878a-a0da534daafd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kioskName']</value>
      <webElementGuid>9e525557-701b-4438-8acb-a8befed34e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authForm']/div/div/div/input</value>
      <webElementGuid>16e82633-b74e-4971-a7f4-7d961fd51664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2c68ed06-8838-4234-9262-8289a43f2866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kioskName']</value>
      <webElementGuid>e4654415-680b-437f-bb58-ff572149d65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
