<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KONVENSIONAL</name>
   <tag></tag>
   <elementGuidId>52a3cabb-0093-4a0b-a529-10647f673734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-red.btn-light-red.button--round-l.no-hover.saving-type > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rekening-pop']/div/div/div[2]/div/ul/li/div/a/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea98e7b1-97c5-4fa0-bea8-91ff9a65d921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>tabungan_regular</value>
      <webElementGuid>cfc8fdee-3ec9-461c-a2ce-d78d45daa5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONVENSIONAL</value>
      <webElementGuid>7351ba41-1db1-4067-aef6-2b84f8db1c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rekening-pop&quot;)/div[@class=&quot;overlay&quot;]/div[@class=&quot;popup-content&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/ul[@class=&quot;l-pop&quot;]/li[1]/div[@class=&quot;text-left&quot;]/a[1]/button[@class=&quot;button btn-red btn-light-red button--round-l no-hover saving-type&quot;]/span[1]</value>
      <webElementGuid>08528227-9517-4edc-80ee-c12ee4514337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rekening-pop']/div/div/div[2]/div/ul/li/div/a/button/span</value>
      <webElementGuid>e6de5fa0-8c12-4c47-b34e-f5548df5ced7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tabungan yang ingin dibuka'])[1]/following::span[1]</value>
      <webElementGuid>32b5c4e3-b1b4-4882-a4e4-9796f0309a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENGKINIAN DATA'])[1]/following::span[1]</value>
      <webElementGuid>3d58e8cb-171d-4987-9efb-0e7e432a0d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYARIAH'])[1]/preceding::span[1]</value>
      <webElementGuid>0fa11cdf-bce5-4ca2-9b01-0a10db0fe4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KONVENSIONAL']/parent::*</value>
      <webElementGuid>3cc2dd0a-1583-41d6-8700-656b621c2fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/button/span</value>
      <webElementGuid>279460eb-4bd7-4b7c-b40d-52411830ce95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KONVENSIONAL' or . = 'KONVENSIONAL')]</value>
      <webElementGuid>c44fe3e9-5b46-4858-b90b-2c1d2b5539c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
