<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BUKA REKENING BARU</name>
   <tag></tag>
   <elementGuidId>66421d49-79e3-466a-95cd-ad215b022c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='HOME']/section[2]/div/div/div/div/div/div[2]/div/div/div/div/a/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9d129f1-8a66-4dce-b624-be3812fa9c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>pembukaan_rekening</value>
      <webElementGuid>48f5b4f3-7cdb-41e3-ab95-1306954321b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUKA REKENING BARU</value>
      <webElementGuid>8cad5605-e5de-4c8d-a565-7fe3c45c2e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HOME&quot;)/section[@class=&quot;SERVICE remove-hide show&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;bg-layanan text-center&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;pad-global add-blur&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-md-offset-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;item-layanan&quot;]/a[@class=&quot;click-rekening&quot;]/button[@class=&quot;min255 button btn-red btn-light-red button--round-l&quot;]/span[1]</value>
      <webElementGuid>3f2c9dd1-c593-4024-b5a1-2a91c463dce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='HOME']/section[2]/div/div/div/div/div/div[2]/div/div/div/div/a/button/span</value>
      <webElementGuid>e4e0e8c3-fcfe-4bfb-88c9-e2bc6b9f811d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih layanan yang diinginkan'])[1]/following::span[1]</value>
      <webElementGuid>59a3334b-e65f-409b-b5b1-69273dfa2a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[1]</value>
      <webElementGuid>e4a5a1a6-a3cc-4706-8021-dee2b4f8b278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENERBITAN KARTU'])[1]/preceding::span[1]</value>
      <webElementGuid>9b08cc57-461b-47ee-b13d-e3b5f6a3834b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENGKINIAN DATA'])[1]/preceding::span[2]</value>
      <webElementGuid>bd7a8f92-b568-4368-947b-b2e9ac3e2c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUKA REKENING BARU']/parent::*</value>
      <webElementGuid>926f102f-8f86-4270-ac19-d58bf7066e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>680ad3f6-84ab-48a6-b9a8-79a3dbcfef78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BUKA REKENING BARU' or . = 'BUKA REKENING BARU')]</value>
      <webElementGuid>f2d799e4-a3a0-4227-8e81-fd582471ad0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
