<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Silakan tunggu sebentar, sedang mengh_20eba5</name>
   <tag></tag>
   <elementGuidId>c6e4ed7f-afe9-483d-afe1-9a13e6fc47da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#videoParent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='videoParent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>4752b0c0-82bc-4ee8-b020-e472e3ea5fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>videoParent</value>
      <webElementGuid>b9226fb0-be60-43c9-aee2-38d02f566019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;videoParent&quot;)</value>
      <webElementGuid>a27b1b70-4c0c-4ff7-ae4c-903a18579f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='videoParent']</value>
      <webElementGuid>746ddb4b-15f8-489e-9b17-9a21ccf8940a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='HOME']/section/a/div/video</value>
      <webElementGuid>51afacb4-ed66-43f8-af8a-1f3e0cea4eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan tunggu sebentar, sedang menghubungkan dengan server'])[1]/following::video[1]</value>
      <webElementGuid>c361ff04-148b-4358-aa9a-8562b7f5afdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang di CIMB Niaga Digital Lounge'])[1]/preceding::video[1]</value>
      <webElementGuid>dbf7caae-1dfb-4b3d-90a8-e384c07eaba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik di manapun untuk memulai'])[1]/preceding::video[1]</value>
      <webElementGuid>de3c6114-0ec4-47ce-bcb8-b03197b6b68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>11af4778-9ba7-43f5-bab8-6b35846d7d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'videoParent']</value>
      <webElementGuid>e11faddb-9934-400c-a240-629ceab9254d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
