<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Syarat dan Ketentuan_mCSB_buttonDown</name>
   <tag></tag>
   <elementGuidId>bba45510-c317-41e2-b191-66857b3f50ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mCSB_buttonDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_scrollbar_vertical']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f9b9bbb-eed1-41dd-916d-0972101f72a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1a55e852-16c4-4a10-952c-e7d79173eafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mCSB_buttonDown</value>
      <webElementGuid>e1a27389-479d-452c-83f6-d9e2e86bb69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_scrollbar_vertical&quot;)/a[@class=&quot;mCSB_buttonDown&quot;]</value>
      <webElementGuid>e1d8b3ab-d301-44f5-8188-c52ec1033398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_scrollbar_vertical']/a[2]</value>
      <webElementGuid>46ba105f-0b1a-4620-a722-4dd4fac8067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>b0827338-9725-4da3-a893-5e2653eeb6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>dc4c8cfe-054b-4059-9907-c322aef0c7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>998cbfdd-5ed7-4b6f-af7c-46439390b0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
