<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Help_mCSB_buttonDown</name>
   <tag></tag>
   <elementGuidId>447fceaa-d89b-49cc-9eee-9ba18371daf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mCSB_buttonDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_scrollbar_vertical']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8f115cf-23a7-4291-af09-dc51d7b4ea82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1bfb03fa-2ea0-4a4b-be20-27b5f1935c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mCSB_buttonDown</value>
      <webElementGuid>ab4c25b7-b894-4a18-952f-a030f6081307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_scrollbar_vertical&quot;)/a[@class=&quot;mCSB_buttonDown&quot;]</value>
      <webElementGuid>22c616e2-e234-481f-93b8-f1fe2a06163f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_scrollbar_vertical']/a[2]</value>
      <webElementGuid>da5d3c22-2a5f-4976-b2d5-2264f96ad207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>a97aa9bb-f063-4e55-82b3-ec8dbe97e7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>c69f9aac-9c6a-4254-b97f-b39321733427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>4f47a650-85ed-44ab-9a0b-270a355f7d84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
