<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_XTRA Savers</name>
   <tag></tag>
   <elementGuidId>e42a7055-e77d-43e2-a576-ff7806719315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-layanan > a > button.button.btn-red.btn-light-red.button--round-l.no-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5653705-7418-474e-8853-98c0c36078b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9860081-801e-42e8-b3ee-eb362621f828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-red btn-light-red button--round-l no-hover</value>
      <webElementGuid>0056627f-8c57-44d0-afc7-89a16772700d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XTRA Savers</value>
      <webElementGuid>68804be6-f427-48b6-bd47-e81f6c866f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;item-layanan&quot;]/a[1]/button[@class=&quot;button btn-red btn-light-red button--round-l no-hover&quot;]</value>
      <webElementGuid>92694bc1-96b5-4668-a8ba-4fbf339f309a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>5a71416f-fe9d-4e37-a949-672a1428a2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/a/button</value>
      <webElementGuid>a6f30bc2-ceee-4166-a2a9-25d1ab6d27bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Rekening yang diinginkan'])[1]/following::button[1]</value>
      <webElementGuid>96d74bc6-5946-4f4a-8d06-bb9fc008d562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KELUAR'])[2]/following::button[1]</value>
      <webElementGuid>2fcdb980-eff5-4e0f-8071-404dd49b6004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEUNTUNGAN PRODUK'])[1]/preceding::button[1]</value>
      <webElementGuid>31e78f17-3f9c-40e3-a17f-fbfe35fc7aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/a/button</value>
      <webElementGuid>a3d7c87b-d20d-457a-ad34-ef66e5844890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'XTRA Savers' or . = 'XTRA Savers')]</value>
      <webElementGuid>184e3430-2b47-4dc0-9296-57d00014dfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
