<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Help_pdf-page-canvas</name>
   <tag></tag>
   <elementGuidId>a41e8295-9bec-4477-add6-dd23bac5c19a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.pdf-page-canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdf-viewer']/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>c5170572-fa73-48a0-9f0f-84d3f82003f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdf-page-canvas</value>
      <webElementGuid>75377aef-a037-4090-8f9d-6cbc9c3d9090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1599</value>
      <webElementGuid>96045ab1-b671-40df-93b3-c7e32020e4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1131</value>
      <webElementGuid>9e624dad-198e-45d1-b8fa-7108926da310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdf-viewer&quot;)/canvas[@class=&quot;pdf-page-canvas&quot;]</value>
      <webElementGuid>efc1dc95-826c-4988-913e-adbb17f74ed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf-viewer']/canvas</value>
      <webElementGuid>0605f145-373c-4d13-a5e9-916ec7c7abad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>75867460-66aa-4d88-ab1c-d41b032cb408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
