<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KONVENSIONAL</name>
   <tag></tag>
   <elementGuidId>025ecf9c-6edb-42ef-9bce-4f43ca9b7df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-red.btn-light-red.button--round-l.no-hover.saving-type > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rekening-pop']/div/div/div[2]/div/ul/li/div/a/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16b67744-c6df-4b1a-b82b-698d4ed61173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>tabungan_regular</value>
      <webElementGuid>b95afe9d-7746-4e03-bb7c-80cb2983c711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONVENSIONAL</value>
      <webElementGuid>e1e8c8d1-8d63-4142-a8ef-70a5d33ae913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rekening-pop&quot;)/div[@class=&quot;overlay&quot;]/div[@class=&quot;popup-content&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/ul[@class=&quot;l-pop&quot;]/li[1]/div[@class=&quot;text-left&quot;]/a[1]/button[@class=&quot;button btn-red btn-light-red button--round-l no-hover saving-type&quot;]/span[1]</value>
      <webElementGuid>9c689c27-9d82-481a-a397-e6b7d488078d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rekening-pop']/div/div/div[2]/div/ul/li/div/a/button/span</value>
      <webElementGuid>9b4b7ab2-bca7-436a-8f3d-10a3732272ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tabungan yang ingin dibuka'])[1]/following::span[1]</value>
      <webElementGuid>567baf15-3e03-40f9-aedd-03baf8103a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENGKINIAN DATA'])[1]/following::span[1]</value>
      <webElementGuid>789a0e76-e6be-4f3a-b4e2-eed3a859968e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYARIAH'])[1]/preceding::span[1]</value>
      <webElementGuid>60fbbc8c-5dca-401d-b20f-3874c335aecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KONVENSIONAL']/parent::*</value>
      <webElementGuid>38319f03-43fc-457b-91da-7cb43f55783d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/button/span</value>
      <webElementGuid>b4771f2b-c6a7-4bc8-8cd7-a93c5066eda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KONVENSIONAL' or . = 'KONVENSIONAL')]</value>
      <webElementGuid>9f65165e-20da-4526-9139-98c6b19c8538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
