<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_SELAMAT Anda berhasil membuka Tabungan GOAL Savers.Berikut adalah Nomor Rekening Anda</name>
   <tag></tag>
   <elementGuidId>0ed97e8b-69f5-423d-8931-37628f883b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>23a973c3-3998-4f12-96fc-ccc7666729a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root jss1247 MuiTypography-body1</value>
      <webElementGuid>99fa5cbb-a7e6-4f09-a27b-c5aac38e2772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>a0a400f9-e9eb-4571-b969-aa677bd70866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELAMAT! Anda berhasil membuka Tabungan GOAL Savers.Berikut adalah Nomor Rekening Anda.</value>
      <webElementGuid>6f1be000-224d-4cad-bce2-d84ecfda2efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)</value>
      <webElementGuid>2bad392e-8cbb-406a-82f3-caa5bea98a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='product']</value>
      <webElementGuid>37cfcffe-8c92-4d85-8311-a5a9b568f4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/p</value>
      <webElementGuid>8e66ce0d-8bed-4114-a7a3-f092a739cdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::p[5]</value>
      <webElementGuid>66de7aaa-6085-41fa-bd24-bddb6ad0d56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::p[5]</value>
      <webElementGuid>b90f6b56-0259-429f-8a15-396667f64e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELAMAT!']/parent::*</value>
      <webElementGuid>dae04fdd-becd-4e0b-b002-2ed6770da85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>e132b813-8132-432c-9322-26695aea124f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'product' and (text() = 'SELAMAT! Anda berhasil membuka Tabungan GOAL Savers.Berikut adalah Nomor Rekening Anda.' or . = 'SELAMAT! Anda berhasil membuka Tabungan GOAL Savers.Berikut adalah Nomor Rekening Anda.')]</value>
      <webElementGuid>5bf0d06c-0f87-401f-9333-2a4dc3ef97bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
