<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Loading_button btn-grey btn-red btn-_5d1c8f</name>
   <tag></tag>
   <elementGuidId>5b38c048-9102-4bd0-9217-98be0396d28f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.btn-grey.btn-red.btn-light-red.button--round-l.no-margin.button-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d8bb845-b44d-4792-bb48-37354d23b138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cad3f0ad-b43a-4f8d-9ace-e9d6b4622576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-grey btn-red btn-light-red button--round-l no-margin button-login</value>
      <webElementGuid>15b02ab5-0e5b-4bdb-8a42-b3e6f9b8f945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>45f75437-2b47-4b26-9ddf-2e871c5fc078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authForm&quot;)/div[@class=&quot;clearfix btn-fixed b20 next-block&quot;]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;button btn-grey btn-red btn-light-red button--round-l no-margin button-login&quot;]</value>
      <webElementGuid>d25a7ff5-631e-47c2-aad0-c9a5a220cefd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='login']</value>
      <webElementGuid>a59b681a-d282-4588-b58e-9dbeddf5f9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authForm']/div[2]/div/button</value>
      <webElementGuid>c326e8dc-e86f-4be6-8e7d-910c8670fbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading ...'])[1]/preceding::button[2]</value>
      <webElementGuid>7990a750-6f1f-41c7-9e45-447073fa7d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ae9ab032-0b49-40f0-9fc8-b163a01c2f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>05d243cc-0d83-4453-b8d1-7a0bb18c1cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
