<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_syarat dan ketentuan</name>
   <tag></tag>
   <elementGuidId>390b2356-60a1-46df-9ce2-399001fe9170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain.'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7557371d-f7c8-4d4e-8bfe-8d9179b22df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19d92f50-feab-4545-a737-0c4600304d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88c8b982-8d1c-44ef-92ac-399e875013da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>5b9c02ca-a621-4296-b6c0-455013d07f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>arrow-down</value>
      <webElementGuid>82e71099-7702-4eb1-a17d-c245ccc12c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-arrow-down fa-w-14 </value>
      <webElementGuid>9cfc46fa-b69e-4d55-b4d9-3329e61ce53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13f84928-1481-4771-aaf1-074f7950d07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>72593e97-2de7-4eda-8b56-3b4e2319fa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>802e4524-6052-4068-9795-f8a1488d6c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss150&quot;]/div[@class=&quot;MuiBox-root jss160 jss151&quot;]/svg[@class=&quot;svg-inline--fa fa-arrow-down fa-w-14&quot;]</value>
      <webElementGuid>8901bc09-46d9-44f2-8939-4ce3b6d764a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain.'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>12927f78-b7f5-4590-a87f-c5357940de64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warga Negara Amerika Serikat atau pemilik kartu Green Card'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>fd4e73d9-1aa2-49f0-9479-6bdebc6a4f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
