<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain</name>
   <tag></tag>
   <elementGuidId>0f808618-f7ff-4351-8672-d55c3364926a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/label[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1c53d20-9c82-4efe-bd1a-d233ecfa782a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiFormControlLabel-label jss158 MuiTypography-body1</value>
      <webElementGuid>28bf002e-4576-4a2d-8b02-4134f83593e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain.</value>
      <webElementGuid>eaf0c1c0-e41c-4575-b559-8d3afde7bf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss150&quot;]/div[@class=&quot;MuiPaper-root MuiCard-root MuiPaper-elevation0 MuiPaper-rounded&quot;]/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiTypography-root MuiFormControlLabel-label jss158 MuiTypography-body1&quot;]</value>
      <webElementGuid>cfe11203-5d93-453b-85f9-68bb90393f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/label[2]/span[2]</value>
      <webElementGuid>0bbd103b-afcd-4010-95cc-90e8df94e47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warga Negara Amerika Serikat atau pemilik kartu Green Card'])[1]/preceding::span[4]</value>
      <webElementGuid>9aa97a53-d58f-4279-870a-5f76d0b4e693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US Indicia (lahir, memilik alamat in care-of atau hold mail, nomor telepon, POA di Amerika Serikat'])[1]/preceding::span[8]</value>
      <webElementGuid>b7122beb-cc7b-4467-9e00-0e448fded3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain.']/parent::*</value>
      <webElementGuid>c5567ba5-b21d-43e9-992d-c00f6e51b8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]</value>
      <webElementGuid>e45d3850-fef2-4b58-b19b-9ed0dd465064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain.' or . = 'Saya adalah wajib pajak Indonesia dan bukan wajib pajak negara lain.')]</value>
      <webElementGuid>6e65e012-87e9-4eb9-ab3f-da8f10a48c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
