<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Help_pdf-page-canvas</name>
   <tag></tag>
   <elementGuidId>68ed1ac2-2b9b-41bc-acc8-7821cc46c9bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.pdf-page-canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdf-viewer']/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>b9493401-80aa-4178-959e-ae4e945f4c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pdf-page-canvas</value>
      <webElementGuid>f5a07104-eec2-4508-881b-acfe58b9a400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1599</value>
      <webElementGuid>af183a6f-756c-49de-a002-769899c437bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1131</value>
      <webElementGuid>7049abf2-5153-4ef2-93d0-14c1d76a086a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdf-viewer&quot;)/canvas[@class=&quot;pdf-page-canvas&quot;]</value>
      <webElementGuid>0cd0f5f6-3513-472a-b393-6aef2c0a0399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf-viewer']/canvas</value>
      <webElementGuid>20fd7a04-34ac-4582-9b35-2f956389a3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>ccebb6cf-7869-4386-948c-332d8d248cd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
