<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Help_mCSB_draggerContainer</name>
   <tag></tag>
   <elementGuidId>0f076014-b4e0-48d4-9650-7d9daa3ecba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mCSB_draggerContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_scrollbar_vertical']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc4115c6-c957-4857-bc04-252a7d378b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mCSB_draggerContainer</value>
      <webElementGuid>2b332a11-6a16-4df0-8af9-6852352dd9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_scrollbar_vertical&quot;)/div[@class=&quot;mCSB_draggerContainer&quot;]</value>
      <webElementGuid>ae358288-08d9-4ad3-8f0d-70fd810de6a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_scrollbar_vertical']/div</value>
      <webElementGuid>3dc8dd4b-e5c2-4e30-92fd-833a85b1e9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::div[9]</value>
      <webElementGuid>a30e326c-b3d3-40ca-9adf-fdc4e9bf2684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::div[10]</value>
      <webElementGuid>aa870544-1407-492e-af2d-df0ac98490dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya telah membaca, memahami, dan menyetujui Ringkasan Informasi Produk dan Layanan (RIPLAY).'])[1]/preceding::div[4]</value>
      <webElementGuid>837fab88-4e61-484b-9d38-e1071f3345b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::div[5]</value>
      <webElementGuid>ac57ef6d-6129-4361-9069-207793f3c046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div</value>
      <webElementGuid>88b4d969-86aa-47c0-a91a-c8154a475624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
