<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_kioskName</name>
   <tag></tag>
   <elementGuidId>4d487a76-1af1-405d-8b02-5ba49cafb916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kioskName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kioskName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e98de45-dc98-42c7-9be9-4183f35e6302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bef97dd7-8d4e-4482-af45-5226ea356d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kioskName</value>
      <webElementGuid>805e0be0-a0bc-4437-a57f-9a0500fad7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-auth required lettersonly input-kiosk input-capital error</value>
      <webElementGuid>87c88de8-0c2e-4c5c-b0f4-1a707e71a90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a052b135-d639-43ec-bc5f-167888c5a13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4682eeef-3dc4-450f-8e4e-065a5bd6be19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authForm&quot;)/div[@class=&quot;step-npwp-success&quot;]/div[@class=&quot;table-tbl&quot;]/div[@class=&quot;cell&quot;]/input[@class=&quot;input-auth required lettersonly input-kiosk input-capital error&quot;]</value>
      <webElementGuid>b1e29ff5-13f7-4181-8b64-31d6e464e551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kioskName']</value>
      <webElementGuid>94339191-ab40-4423-a378-80de6a64caeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='authForm']/div/div/div/input</value>
      <webElementGuid>4d81be87-5ac1-4edd-92ff-e7b246aa3073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>452a1dd3-828e-430a-afb8-d2db3966e8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kioskName']</value>
      <webElementGuid>7547aa76-e6c3-44c3-888b-e9d66c22ad25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
