<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Silakan tunggu sebentar, sedang mengh_20eba5</name>
   <tag></tag>
   <elementGuidId>e8c2d66b-05ea-4950-9f14-d7f5c5fe4a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#videoParent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='videoParent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>e1ce08b2-3022-40a7-9189-9051c9c29f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>videoParent</value>
      <webElementGuid>2eada462-601f-44db-860e-5809a0f921c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;videoParent&quot;)</value>
      <webElementGuid>9332cd12-3f46-4561-a22c-e8119151bee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='videoParent']</value>
      <webElementGuid>361e3867-1c27-4e71-940d-2e2d3cba2d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='HOME']/section/a/div/video</value>
      <webElementGuid>a0d73487-6154-408a-980e-80600bb2cb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan tunggu sebentar, sedang menghubungkan dengan server'])[1]/following::video[1]</value>
      <webElementGuid>f97c5fb1-174d-4189-bee1-f4b24a3f9775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang di CIMB Niaga Digital Lounge'])[1]/preceding::video[1]</value>
      <webElementGuid>18da38bd-3a4d-4678-9509-e1d5b339b48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik di manapun untuk memulai'])[1]/preceding::video[1]</value>
      <webElementGuid>bf353619-7c6c-4acf-b695-379c0e84243f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>8e7baf4d-73b8-44c2-a711-c7655d40c88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'videoParent']</value>
      <webElementGuid>68fb725e-319b-499d-88ad-62760efa3c97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
